# This is an example of a TOML configuration file for a arduino baesed PLC using MODBUS
title = "Arduino PLC Configuration Example"
version = "1.0"
target = "arduino mega 2560" # specify the target PLC model

[modbus]
type = "IP" # options are IP or Serial
ip_address = "10.1.10.101" # ignore or not needed if type is Serial
port = 502 # ignore or not needed if type is Serial
slave_id = 1    # The slave ID of the PLC, used for addressing in MODBUS communication

[registers]

coils = [
    {register = 1, pin = "2", description = "DO1"},
    {register = 2, pin = "3", description = "DO2"},
    {register = 3, pin = "4", description = "DO3"},
    {register = 4, pin = "5", description = "DO4"},
    {register = 5, pin = "6", description = "DO5"},
    {register = 6, pin = "7", description = "DO6"},
    {register = 7, pin = "8", description = "DO7"},
]

discrete_inputs = [
    {register = 101, pin = "22", description = "DI1"},
    {register = 102, pin = "23", description = "DI2"},
    {register = 103, pin = "24", description = "DI3"},
    {register = 104, pin = "25", description = "DI4"},
    {register = 105, pin = "26", description = "DI5"},
    {register = 106, pin = "27", description = "DI6"},
    {register = 107, pin = "28", description = "DI7"},
]

input_registers = [
    {register = 201, pin = "A0", description = "AI1"},
    {register = 202, pin = "A1", description = "AI2"},
    {register = 203, pin = "A2", description = "AI3"},
    {register = 204, pin = "A3", description = "AI4"},
    {register = 205, pin = "A4", description = "AI5"},
    {register = 206, pin = "A5", description = "AI6"},
    {register = 207, pin = "A6", description = "AI7"},
]

holding_registers = [
    {register = 301, pin = "9",  description = "AO1", range = [0, 255]},
    {register = 302, pin = "10", description = "AO2", range = [0, 255]},
    {register = 303, pin = "11", description = "AO3", range = [0, 255]},
    {register = 304, pin = "12", description = "AO4", range = [0, 255]},
    {register = 305, pin = "13", description = "AO5", range = [0, 255]},
]

genRegs = [
    {register = 350, description = "General Purpose Register 1", range = [0, 100]},
    {register = 351, description = "General Purpose Register 2", range = [0, 100]},
    {register = 352, description = "General Purpose Register 3", range = [0, 100]},
    {register = 353, description = "General Purpose Register 4", range = [0, 100]},
    {register = 354, description = "General Purpose Register 5", range = [0, 100]},
] # gen regs are regs that are not connected to pins and can be read or written to, 
# these are HOLDING REGISTERS but they can be used for any purpose, they are just not connected to any pins

genFlags = [
    {register = 50, description = "System Fault Flag"},
    {register = 51, description = "Invalid Register Value Flag"},
    {register = 52, description = "General Purpose Flag 3"},
    {register = 53, description = "General Purpose Flag 4"},
    {register = 54, description = "General Purpose Flag 5"},
] # gen flags are flags that are not connected to pins and can be read or written to, 
# these are COILS but they can be used for any purpose, they are just not connected to any pins