[env:controllino_mega]
platform = atmelavr
board = controllino_mega
framework = arduino

lib_deps =
    emelianov/modbus-esp8266@^4.1.0
    arduino-libraries/Ethernet@^2.0.0
    CONTROLLINO-PLC/CONTROLLINO@^3.0.6
